<a href="https://colab.research.google.com/github/2403A51L17/2403A51L17_Batch--51_PDS/blob/main/Lab2_student_grade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [92, 88, 76],
    [65, 70, 80],
    [89, 94, 91],
    [55, 60, 72]
])

print("Student Marks:\n", marks)

average_marks = np.mean(marks, axis=1)
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)

print("\nAverage Marks of Students:", average_marks)
print("Minimum Marks of Students:", min_marks)
print("Maximum Marks of Students:", max_marks)

student2_marks = marks[1, :]
print("\nMarks of Student 2:", student2_marks)

above_80 = marks > 80
print("\nBoolean Matrix (True = score > 80):\n", above_80)

students_above_80 = np.any(marks > 80, axis=1)
print("\nStudents scoring above 80 (True=Yes):", students_above_80)

reshaped = marks.T
print("\nSubject-wise Performance:\n", reshaped)

subject_avg = np.mean(reshaped, axis=1)
subject_min = np.min(reshaped, axis=1)
subject_max = np.max(reshaped, axis=1)

print("\nAverage per Subject:", subject_avg)
print("Minimum per Subject:", subject_min)
print("Maximum per Subject:", subject_max)

print("\n--- Analysis ---")
print("Student 4 has the highest average score.")
print("Student 5 has the lowest average score.")
print("Subject 3 is the best-performing subject overall.")
print("Subject 1 is the weakest subject overall.")


Student Marks:
 [[78 85 90]
 [92 88 76]
 [65 70 80]
 [89 94 91]
 [55 60 72]]

Average Marks of Students: [84.33333333 85.33333333 71.66666667 91.33333333 62.33333333]
Minimum Marks of Students: [78 76 65 89 55]
Maximum Marks of Students: [90 92 80 94 72]

Marks of Student 2: [92 88 76]

Boolean Matrix (True = score > 80):
 [[False  True  True]
 [ True  True False]
 [False False False]
 [ True  True  True]
 [False False False]]

Students scoring above 80 (True=Yes): [ True  True False  True False]

Subject-wise Performance:
 [[78 92 65 89 55]
 [85 88 70 94 60]
 [90 76 80 91 72]]

Average per Subject: [75.8 79.4 81.8]
Minimum per Subject: [55 60 72]
Maximum per Subject: [92 94 91]

--- Analysis ---
Student 4 has the highest average score.
Student 5 has the lowest average score.
Subject 3 is the best-performing subject overall.
Subject 1 is the weakest subject overall.
