<a href="https://colab.research.google.com/github/2403A51L17/2403A51L17_Batch--51_PDS/blob/main/Lab_3_2d_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

matrix1 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])

matrix2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

dot_product_np = np.dot(matrix1, matrix2)
print("\nDot product using np.dot():")
print(dot_product_np)

dot_product_at = matrix1 @ matrix2
print("\nDot product using @ operator:")
print(dot_product_at)

print("\nAre the results from np.dot() and @ operator the same?")
print(np.array_equal(dot_product_np, dot_product_at))


filter_kernel = np.array([[1/9, 1/9, 1/9],
                          [1/9, 1/9, 1/9],
                          [1/9, 1/9, 1/9]])

print("\nExample of a filter kernel (simplified):")
print(filter_kernel)

Matrix 1:
[[1 2]
 [3 4]
 [5 6]]

Matrix 2:
[[ 7  8  9]
 [10 11 12]]

Dot product using np.dot():
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]

Dot product using @ operator:
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]

Are the results from np.dot() and @ operator the same?
True

Example of a filter kernel (simplified):
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
