<a href="https://colab.research.google.com/github/2403A51L17/2403A51L17_Batch--51_PDS/blob/main/Lab_3_3d_matrix_add_and_sub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.random.randint(1, 50, (3, 3))
B = np.random.randint(1, 50, (3, 3))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

add_result = np.add(A, B)
print("\nMatrix Addition (A + B):\n", add_result)

sub_result = np.subtract(A, B)
print("\nMatrix Subtraction (A - B):\n", sub_result)

manual_add = A[0, 0] + B[0, 0]
manual_sub = A[0, 0] - B[0, 0]
print(f"\nVerification for element (0,0): {A[0,0]} + {B[0,0]} = {manual_add}, "
      f"{A[0,0]} - {B[0,0]} = {manual_sub}")


Matrix A:
 [[38 13 48]
 [ 4 31 31]
 [17 29 19]]

Matrix B:
 [[38 23 20]
 [21 19 28]
 [21 20 19]]

Matrix Addition (A + B):
 [[76 36 68]
 [25 50 59]
 [38 49 38]]

Matrix Subtraction (A - B):
 [[  0 -10  28]
 [-17  12   3]
 [ -4   9   0]]

Verification for element (0,0): 38 + 38 = 76, 38 - 38 = 0
